### ISSUE TITLE
Clicking a kata link in the katas navigation does not load kata

### ISSUE THREAD

**Issue by martinandert** [tddbin/tddbin-frontend#14]
Clicking one of the kata links in the footer navigation updates the location hash in the browser address bar but doesn't actually load the kata. Is this a feature? Shouldn't the app listen to the `hashchange` event?

On a side note: Could you elaborate on why the kata gets removed from the `location.hash` on startup? See [startup.js line 16](https://github.com/tddbin/tddbin-frontend/blob/16179512490793773105ba4a098dbacd982ba174/src/startup.js#L16)

**Comment by MichaelKatz** [comment]
+1 for this one.

**Comment by wolframkriesing** [comment]
oh man ... this is actually so kaputt (the reasoning why hash etc.) :) I have an update which will use standard queries, see here https://github.com/tddbin/tddbin-frontend/tree/use-query-param-refactoring

**Comment by wolframkriesing** [comment]
reviews to https://github.com/tddbin/tddbin-frontend/pull/16 welcome

**Comment by wolframkriesing** [comment]
fixed by 1bc0b92a95342839511e42bdeeaf0631561a7c70
