### ISSUE TITLE
iterator - string - test description is wrong

### ISSUE THREAD

**Issue by chiptus** [tddbin/tddbin-frontend#17]
The last test on the iterator - string kata is wrong, i think it should say done=true, that's also what the assert ask for...

Great project by the way, would love to hear if you need any help

**Comment by tddbin** [comment]
Oh right, the text above is wrong. Thanks for finding it.
If you want to you can write katas see github.com/tddbin/katas
PRs very welcome
Am 02.07.2015 18:37 schrieb "chiptus" <notifications@github.com>:

**Comment by tddbin** [comment]
Fix is on the way
Wolfram
Am 02.07.2015 19:08 schrieb "Wolfram Kriesing" <kriesing@uxebu.com>:

**Comment by wolframkriesing** [comment]
does this fix it?
https://github.com/tddbin/katas/commit/9be329e87e991e88b647c5af1a8b8b7d855151f8
closing it, hope thats ok

**Comment by chiptus** [comment]
great, thanks!
