### ISSUE TITLE
Integrate the ace editor to have autocompletion and other features

### ISSUE THREAD

**Issue by jeffeland** [tddbin/tddbin-frontend#2]
Here is the editor : http://ace.c9.io/#nav=about
which I found really nice to use in https://www.codeeval.com

**Comment by wolframkriesing** [comment]
Tdd bin does use ace right now ;)
Am 07.03.2015 21:36 schrieb "Jean-Francois Landreau" <
notifications@github.com>:

**Comment by jeffeland** [comment]
Oh ok. But the auto-completion doesn't work for some reason.

**Comment by wolframkriesing** [comment]
you are right, the autocompletion was turned on, but didn't work. in the worx

**Comment by wolframkriesing** [comment]
does it work for you now?
