### ISSUE TITLE
Answers of your exercises

### ISSUE THREAD

**Issue by underwindfall** [tddbin/tddbin-frontend#38]
Hello there, 
 I have learned ES6 recently and I found your site which helped me a lot.  However when I used your site to study ES6 sometimes it was really hard for me to get correct answers.
So I writed down a part of answers  in my [Github Gist](https://gist.github.com/underwindfall) and I'll update it as soon as I can.
Hope your guys will like it.

**Comment by underwindfall** [comment]
All answers are done . Enjoy coding!

**Comment by wolframkriesing** [comment]
Hi, cool that you found all the answers. I have to say, that I enjoy
redoing the katas from time to time, esp. when I need to remember how a
certain feature works. Therefore is see a value in getting to the answer by
doing it and not looking them up, also multiple times.
Enjoy


Am 05.03.2017 11:46 nachm. schrieb "undervoid" <notifications@github.com>:

**Comment by underwindfall** [comment]
@wolframkriesing  You're quite right. The result is not important, the most important is process.
