### ISSUE TITLE
speed up the user's learning process

### ISSUE THREAD

**Issue by dearfrankg** [tddbin/tddbin-frontend#7]
You learn faster when the answers are provided when needed.  Please work that into this app.

**Comment by wolframkriesing** [comment]
Hi,
can you please elaborate a bit? The kata is meant to be for figuring out the solution yourself, I think the answer would not serve that purpose, in my opinion.
Wolfram

**Comment by dearfrankg** [comment]
A kata is like a drill that you can do over and over for practice.  I'm not saying the user should not think, but what happens when the user doesn't know the answer? - They have to go elsewhere to go hunt it down.  If they can get the answer by clicking on a button that saves them a lot of time.  Then they can redo the kata and not have to use the answer-button the second time around.  The result is that they can get up to speed much quicker.

**Comment by wolframkriesing** [comment]
Hi Frank,

thanks for the input. The name kata might be misleading here I agree. I
thought it had charme and makes the learning even deeper when you have to
go figure out things, or better try them out, from the mistake you learn.
I am intending the katas to be built that way that you can go from top to
bottom and learn the according feature. If that doesnt work the kata might
needs better explaination.
On the es6katas.org site I agree there could be some additional links +
hints.

--
Kind regards / Saludos / Mit freundlichen Grüßen
Wolfram Kriesing, uxebu Co-Founder

kriesing@uxebu.com, mobile: +49 174 300 4595

ECMAScript6+React.js workshop http://meetu.ps/2Jds4D
Learn ES6, one kata a day http://es6katas.org

uxebu GmbH
Fraunhofer Straße 31e
86167 Augsburg

Amtsgericht Augsburg, Handelsregister HRB 28613
Directors: W. Kriesing, T. v. Klipstein

**Comment by dearfrankg** [comment]
Thanks for the conversation.  Good luck.
