### ISSUE TITLE
arrow function binding test 2

### ISSUE THREAD

**Issue by Jks15063** [tddbin/tddbin-frontend#8]
Seems like the test should be `assert.strictEqual(fn.call(anotherObj), bound);`, the same as test one, since you are proving that a new context can't be provided.

**Comment by wolframkriesing** [comment]
Do you mean this test here?
https://github.com/tddbin/katas/blob/master/katas/es6/language/arrow-functions/binding.js#L16
or another one?
All katas are stored in this repo https://github.com/tddbin/katas

**Comment by Jks15063** [comment]
That's it :)

**Comment by wolframkriesing** [comment]
is that broken?

**Comment by Jks15063** [comment]
I guess there is not any other way to make it fail.

If you change it to`assert.strictEqual(fn.call(anotherObj), bound);` then it always passes, 

`var anotherObj = {};
    assert.strictEqual(fn.call(anotherObj), anotherObj);` just seemed really strange way to compare, I think I just needed to sleep on it :P

**Comment by wolframkriesing** [comment]
I think I know what you mean
```js
it('can NOT bind a different context', function() {
    var bound = new LexicallyBound();
    var fn = bound.getFunction();
    var anotherObj = {};
    assert.strictEqual(fn.call(anotherObj), anotherObj);
});
```
would better be
```js
it('can NOT bind a different context', function() {
    var bound = new LexicallyBound();
    var fn = bound.getFunction();

    var anotherObj = {};
    var functionResult = fn.call(anotherObj);

    assert.strictEqual(functionResult, anotherObj);
});
```
more explicit of what is compared, is that what could be improved?

**Comment by Jks15063** [comment]
That looks a little better.  I honestly think I just needed some sleep.  Thanks for taking a look at it though.
